-- ============================================
-- 此文件由云服务自动生成，请勿手动修改
-- This file is auto-generated by meoo cloud service, DO NOT MODIFY
-- ============================================

-- 创建考生表
CREATE TABLE IF NOT EXISTS public.students (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  class_name TEXT NOT NULL DEFAULT '24物流1班',
  name TEXT NOT NULL,
  seat_number TEXT NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  UNIQUE(name, seat_number)
);

-- 创建考试成绩表
CREATE TABLE IF NOT EXISTS public.exam_results (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  student_id UUID NOT NULL REFERENCES public.students(id) ON DELETE CASCADE,
  chapter_id INTEGER NOT NULL,
  score INTEGER NOT NULL,
  correct_count INTEGER NOT NULL,
  total_count INTEGER NOT NULL DEFAULT 40,
  time_used INTEGER NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 创建管理员表
CREATE TABLE IF NOT EXISTS public.admins (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  username TEXT NOT NULL UNIQUE,
  password TEXT NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 插入默认管理员
INSERT INTO public.admins (username, password) 
VALUES ('admin', 'admin123')
ON CONFLICT (username) DO NOTHING;

-- 启用RLS
ALTER TABLE public.students ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.exam_results ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.admins ENABLE ROW LEVEL SECURITY;

-- 学生表策略：允许匿名插入和查询
CREATE POLICY "允许匿名注册考生" ON public.students
  FOR INSERT WITH CHECK (true);

CREATE POLICY "允许匿名查询考生" ON public.students
  FOR SELECT USING (true);

-- 成绩表策略：允许匿名插入和查询
CREATE POLICY "允许匿名提交成绩" ON public.exam_results
  FOR INSERT WITH CHECK (true);

CREATE POLICY "允许匿名查询成绩" ON public.exam_results
  FOR SELECT USING (true);

-- 管理员表策略：仅允许查询
CREATE POLICY "允许匿名查询管理员" ON public.admins
  FOR SELECT USING (true);